"""Drop game table

Revision ID: 75a4b33ae0b9
Revises: 3acfd87a5ade
Create Date: 2024-09-12 14:06:33.463867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a4b33ae0b9'
down_revision = '3acfd87a5ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('player_o_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_turn',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wins',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('losses',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('draws',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('draws',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('losses',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wins',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('current_turn',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('player_o_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grid_size', sa.INTEGER(), nullable=False),
    sa.Column('player_x_id', sa.INTEGER(), nullable=False),
    sa.Column('player_o_id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('current_turn', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['player_o_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_x_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
