"""Add current_turn column to game table

Revision ID: a162f2db525b
Revises: 4e919db179d4
Create Date: 2024-09-10 14:30:14.502417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a162f2db525b'
down_revision = '4e919db179d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_turn', sa.String(), nullable=True))
        batch_op.alter_column('player_o_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('player_o_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('current_turn')

    # ### end Alembic commands ###
